name: Build openSUSE App Only

on:
  push:
    branches: [ "main" ]

jobs:
  build-suse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: node ./scripts/build.mjs

      - name: Install RPM build tools
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build Electron RPM installer
        run: npx electron-builder --linux rpm --publish never

      - name: Upload openSUSE installer
        uses: actions/upload-artifact@v4
        with:
          name: opensuse-installer
          path: dist/*.rpm
